// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDky1c6r9IjoB1O_TU6FsWwm19jnI3WOEs',
    appId: '1:1093239873458:web:0918707ca0e9426f7d4eab',
    messagingSenderId: '1093239873458',
    projectId: 'resumecraftai-46ae3',
    authDomain: 'resumecraftai-46ae3.firebaseapp.com',
    storageBucket: 'resumecraftai-46ae3.firebasestorage.app',
    measurementId: 'G-E7Z5ZGZHTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9d5ZkMLvp7X9_d5XVtZrviIO3_SzGPw',
    appId: '1:1093239873458:android:100a3dd1484a7bb07d4eab',
    messagingSenderId: '1093239873458',
    projectId: 'resumecraftai-46ae3',
    storageBucket: 'resumecraftai-46ae3.firebasestorage.app',
  );
}
